# Generated by Django 2.1.5 on 2019-02-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='sluug',
            new_name='slug',
        ),
    ]
